name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: misago
          POSTGRES_PASSWORD: misago
          POSTGRES_DB: misago
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: devproject.test_settings
          POSTGRES_DB: misago
          POSTGRES_USER: misago
          POSTGRES_PASSWORD: misago
          POSTGRES_HOST: localhost
        run: | 
          pytest --no-cov --splits 10 --group ${{ matrix.group }}
